from . import tabulations_criteria
from . import tabulations_events
from . import tabulations_judges
from . import tabulations_participants
from . import tabulations_scorecards
from . import tabulations_session
from . import tabulations_teams
from . import tabulations_dashboard
from . import tabulations_config